#### Importing Libraries

In [67]:
import pandas as pd
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
from imblearn.combine import SMOTEENN
from sklearn.model_selection import GridSearchCV
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier

#### Reading csv file

In [ ]:
import os
os.chdir('C:\\Users\\ACER\\Downloads\\Telco Customer Churn Python Project')

In [43]:
df=pd.read_csv('telco_data.csv')
df.head()
df.shape

(7032, 52)

In [31]:
df.drop('Unnamed: 0',axis=1,inplace=True)
df.head()

,SeniorCitizen,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,29.85,29.85,0,1,0,0,1,1,0,...,0,0,1,0,1,0,0,0,0,0
1,0,56.95,1889.50,0,0,1,1,0,1,0,...,0,0,0,1,0,0,1,0,0,0
2,0,53.85,108.15,1,0,1,1,0,1,0,...,0,0,0,1,1,0,0,0,0,0
3,0,42.30,1840.75,0,0,1,1,0,1,0,...,1,0,0,0,0,0,0,1,0,0
4,0,70.70,151.65,1,1,0,1,0,1,0,...,0,0,1,0,1,0,0,0,0,0

In [32]:
# Splitting data into X and Y variables
X = df.drop('Churn',axis=1)
Y = df.Churn

##### Train Test Split

In [33]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2)

In [34]:
x_train.head()

,SeniorCitizen,MonthlyCharges,TotalCharges,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,PhoneService_No,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
210,0,46.0,84.50,0,1,1,0,1,0,0,...,0,1,0,0,1,0,0,0,0,0
5522,0,44.8,2983.65,0,1,0,1,0,1,1,...,0,0,0,1,0,0,0,0,0,1
1104,0,24.6,1678.05,1,0,1,0,1,0,0,...,0,1,0,0,0,0,0,0,0,1
2651,0,59.3,2209.15,1,0,1,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
6210,1,25.7,25.70,1,0,1,0,1,0,1,...,0,0,0,1,1,0,0,0,0,0

In [35]:
y_train.head()

210     1
5522    0
1104    0
2651    0
6210    1
Name: Churn, dtype: int64

#### Decision Tree Classifier

In [36]:
model_dt_1 = DecisionTreeClassifier()
model_dt_1.fit(x_train,y_train)

DecisionTreeClassifier()

In [37]:
print(classification_report(y_train,model_dt_1.predict(x_train)))
print(classification_report(y_test,model_dt_1.predict(x_test)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4133
           1       1.00      0.99      1.00      1492

    accuracy                           1.00      5625
   macro avg       1.00      1.00      1.00      5625
weighted avg       1.00      1.00      1.00      5625

              precision    recall  f1-score   support

           0       0.82      0.82      0.82      1030
           1       0.50      0.50      0.50       377

    accuracy                           0.73      1407
   macro avg       0.66      0.66      0.66      1407
weighted avg       0.73      0.73      0.73      1407

#### Hyperparameter Tuning on Decision Tree

In [38]:
param_grid = {'criterion':['gini','entropy'],
             'max_depth':range(3,8),
             'max_leaf_nodes':range(3,12),
             'class_weight':['balanced']}

model_dt_2 = GridSearchCV(DecisionTreeClassifier(),param_grid=param_grid,cv=3,scoring='recall')
model_dt_2.fit(x_train,y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'class_weight': ['balanced'],
                         'criterion': ['gini', 'entropy'],
                         'max_depth': range(3, 8),
                         'max_leaf_nodes': range(3, 12)},
             scoring='recall')

In [39]:
model_dt_2.best_score_
model_dt_2.best_params_

{'class_weight': 'balanced',
 'criterion': 'gini',
 'max_depth': 3,
 'max_leaf_nodes': 3}

In [40]:
model_dt_2 = model_dt_2.best_estimator_

In [41]:
print(classification_report(y_train,model_dt_2.predict(x_train)))
print(classification_report(y_test,model_dt_2.predict(x_test)))

              precision    recall  f1-score   support

           0       0.93      0.57      0.71      4133
           1       0.43      0.89      0.58      1492

    accuracy                           0.65      5625
   macro avg       0.68      0.73      0.64      5625
weighted avg       0.80      0.65      0.67      5625

              precision    recall  f1-score   support

           0       0.93      0.57      0.71      1030
           1       0.43      0.88      0.58       377

    accuracy                           0.65      1407
   macro avg       0.68      0.73      0.64      1407
weighted avg       0.80      0.65      0.67      1407

#### SMOTE

In [44]:
sm = SMOTEENN()
x_dres,y_dres = sm.fit_resample(X,Y)

In [57]:
x_dres.shape

(5885, 50)

In [48]:
X.shape

(7032, 50)

In [50]:
xr_train,xr_test,yr_train,yr_test = train_test_split(x_dres,y_dres,test_size=0.2)

In [51]:
model_dt_3 = DecisionTreeClassifier(class_weight='balanced',criterion='gini',max_depth= 3,max_leaf_nodes=3)
model_dt_3.fit(xr_train,yr_train)

DecisionTreeClassifier(class_weight='balanced', max_depth=3, max_leaf_nodes=3)

In [52]:
print(classification_report(yr_train,model_dt_3.predict(xr_train)))
print(classification_report(yr_test,model_dt_3.predict(xr_test)))

              precision    recall  f1-score   support

           0       0.86      0.74      0.80      2147
           1       0.80      0.90      0.85      2561

    accuracy                           0.83      4708
   macro avg       0.83      0.82      0.82      4708
weighted avg       0.83      0.83      0.83      4708

              precision    recall  f1-score   support

           0       0.87      0.74      0.80       522
           1       0.82      0.91      0.86       655

    accuracy                           0.84      1177
   macro avg       0.84      0.83      0.83      1177
weighted avg       0.84      0.84      0.83      1177

Hence, model_dt_3 built on balanced data is the best model so far.

#### Random Forest Classifier

In [68]:
model_rf_1 = RandomForestClassifier()
model_rf_1.fit(x_train,y_train)
print(classification_report(y_train,model_rf_1.predict(x_train)))
print(classification_report(y_test,model_rf_1.predict(x_test)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4133
           1       1.00      0.99      1.00      1492

    accuracy                           1.00      5625
   macro avg       1.00      1.00      1.00      5625
weighted avg       1.00      1.00      1.00      5625

              precision    recall  f1-score   support

           0       0.82      0.91      0.87      1030
           1       0.66      0.47      0.55       377

    accuracy                           0.79      1407
   macro avg       0.74      0.69      0.71      1407
weighted avg       0.78      0.79      0.78      1407

#### Hyperparameter tuning on Random Forest Classifier

In [69]:
param_grid = {'n_estimators':[100,150,200,250],'criterion':['gini','entropy'],'max_depth':range(3,10)}

model_rf_2 = GridSearchCV(RandomForestClassifier(),param_grid=param_grid,cv=3,scoring='recall')
model_rf_2.fit(x_train,y_train)

GridSearchCV(cv=3, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': range(3, 10),
                         'n_estimators': [100, 150, 200, 250]},
             scoring='recall')

In [70]:
model_rf_2.best_score_

0.4839195817475132

In [71]:
model_rf_2.best_params_

{'criterion': 'gini', 'max_depth': 9, 'n_estimators': 250}

In [72]:
model_rf_2 = model_rf_2.best_estimator_

In [73]:
print(classification_report(y_train,model_rf_2.predict(x_train)))
print(classification_report(y_test,model_rf_2.predict(x_test)))

              precision    recall  f1-score   support

           0       0.87      0.94      0.90      4133
           1       0.77      0.60      0.67      1492

    accuracy                           0.85      5625
   macro avg       0.82      0.77      0.79      5625
weighted avg       0.84      0.85      0.84      5625

              precision    recall  f1-score   support

           0       0.84      0.92      0.88      1030
           1       0.71      0.52      0.60       377

    accuracy                           0.81      1407
   macro avg       0.77      0.72      0.74      1407
weighted avg       0.80      0.81      0.80      1407

#### On balanced dataset got after SMOTE

In [74]:
model_rf_3 = RandomForestClassifier(n_estimators=150,criterion='gini',random_state=42,max_depth=9)
model_rf_3.fit(xr_train,yr_train)

RandomForestClassifier(max_depth=9, n_estimators=150, random_state=42)

In [75]:
print(classification_report(yr_train,model_rf_3.predict(xr_train)))
print(classification_report(yr_test,model_rf_3.predict(xr_test)))

              precision    recall  f1-score   support

           0       0.98      0.95      0.96      2147
           1       0.96      0.98      0.97      2561

    accuracy                           0.97      4708
   macro avg       0.97      0.97      0.97      4708
weighted avg       0.97      0.97      0.97      4708

              precision    recall  f1-score   support

           0       0.97      0.93      0.95       522
           1       0.95      0.98      0.96       655

    accuracy                           0.96      1177
   macro avg       0.96      0.95      0.96      1177
weighted avg       0.96      0.96      0.96      1177

#### Hence, the best model we got so far is model_rf_3 i.e Random Forest Classifier on balanced dataset.